### ISSUE TITLE
Translation configuration by field type rather than name

### ISSUE THREAD

**Issue by foxacid** [johannschopplich/kirby-content-translator#14]
First of all the plugin is awesome and works really well.

However, configuration for larger, more complex sites is problematic. Specifically whitelisting every single field to be translated via its name is not a practical solution as this potentially creates huge lists. Would it be possible to invert the behaviour, i.e. translate by field types instead of field name? The fields that should not be translated could be passed to an `excludeFields` array...

Or is there another way to prevent going over dozens of templates and fields and pick out every single field name for the translation?

**Comment by foxacid** [comment]
Actually it seems that this has already been implemented for blocks. Quoting from the documentation:

> By default, all built-in Kirby blocks that include a text-like field are pre-configured to be translated.

**Comment by johannschopplich** [comment]
This has been resolved with the [Kirby Content Translator v2](https://kirby.tools/content-translator), which is a complete rewrite and supports translating fields by type, rather than their name.

See the [`fieldTypes` section configuration](https://kirby.tools/docs/content-translator/configuration#fieldtypes).
